on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: {}

name: Refresh Strava Credentials

jobs:
  refesh-creds:
    runs-on: ubuntu-latest
    name: Refresh Strava Credentials
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Fetch credentials
        env:
          STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
          STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
        run: |
          eval "$(./scripts/refresh_strava_credentials.ts)"
          echo "::add-mask::${STRAVA_ID}"
          echo "::add-mask::${STRAVA_COOKIES}"
          echo "STRAVA_ID=${STRAVA_ID}" >> $GITHUB_ENV
          echo "STRAVA_COOKIES=${STRAVA_COOKIES}" >> $GITHUB_ENV

      - name: Write Strava creds to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            STRAVA_ID
            STRAVA_COOKIES

      - name: Update last refresh timestamp
        run: |
          echo "{\"last_refresh\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > last_refresh.json

      - name: Commit last refresh timestamp
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add last_refresh.json
          git commit -m "Update last refresh timestamp" || exit 0
          git push